### ISSUE TITLE
依赖库提问

### ISSUE THREAD

**Issue by Jianyi2004** [qzp2018/AnyTrans#2]
可以问一下本仓库的python版本，modelscope版本和datasets版本，我现在用的是python3.9,datasets==2.12.0，但是版本号不太匹配，出现报错：
```
Traceback (most recent call last):
  File "/data/zjy/imagetrans/AnyTrans/main_code.py", line 23, in <module>
    from modelscope.pipelines import pipeline
  File "/data/zjy/anaconda3/envs/anytrans/lib/python3.9/site-packages/modelscope/pipelines/__init__.py", line 4, in <module>
    from .base import Pipeline
  File "/data/zjy/anaconda3/envs/anytrans/lib/python3.9/site-packages/modelscope/pipelines/base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "/data/zjy/anaconda3/envs/anytrans/lib/python3.9/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from modelscope.msdatasets.ms_dataset import MsDataset
  File "/data/zjy/anaconda3/envs/anytrans/lib/python3.9/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
  File "/data/zjy/anaconda3/envs/anytrans/lib/python3.9/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 19, in <module>
    from datasets.data_files import (
ImportError: cannot import name 'get_metadata_patterns' from 'datasets.data_files' (/data/zjy/anaconda3/envs/anytrans/lib/python3.9/site-packages/datasets/data_files.py)
```

**Comment by qzp2018** [comment]
你好，我的环境是基于AnyText的，你可以参考AnyText的环境。并且目前上传的代码是没法直接跑通的，因为我当时调用的是公司的LLM和擦图api。你可以基于我的链路使用自己的LLM和擦图模型。
